/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebab2;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ESFOT
 */
public class Usuario extends javax.swing.JFrame {

    ArrayList <Cliente> clientes= new  ArrayList<>();
    ArrayList <Frutas> productos= new  ArrayList<>();
    
   
    
    public Usuario() {
        initComponents();
        crearProductos();
        cargarPoductos();
        cargarClientes();
    }
    
    public void crearProductos(){
        Frutas objProducto1= new Frutas("12","Manzana", 0.30);
        Frutas objProducto2= new Frutas("15","Pera", 0.55);
        Frutas objProducto3= new Frutas("10","Piña", 0.75);
        Frutas objProducto4= new Frutas("18","Frutilla", 0.40);
        Frutas objProducto5= new Frutas("13","Coco", 0.60);
        
        productos.add(objProducto1);
        productos.add(objProducto2);
        productos.add(objProducto3);
        productos.add(objProducto4);
        productos.add(objProducto5);
    }
    
    public void cargarPoductos(){
        
      if(productos.isEmpty()){
      cbListaFrutas.setEnabled(false);    
      }else{
      cbListaFrutas.setModel(new javax.swing.DefaultComboBoxModel(productos.toArray()));
      cbListaFrutas.setEnabled(true);    
      
      }
    }
    public void cargarClientes(){
         if(clientes.isEmpty()){
     cmbCedulas.setEnabled(false);    
      }else{
      cmbCedulas.setModel(new javax.swing.DefaultComboBoxModel(clientes.toArray()));
      cmbCedulas.setEnabled(true);    
      
         }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JPanel();
        jblNombre = new javax.swing.JLabel();
        textNombreUsuario = new javax.swing.JTextField();
        jblCedula = new javax.swing.JLabel();
        textCedulaUsuario = new javax.swing.JTextField();
        jblListaFrutas = new javax.swing.JLabel();
        cbListaFrutas = new javax.swing.JComboBox<>();
        jblCodigoFrutas = new javax.swing.JLabel();
        textCodigoFrutas = new javax.swing.JTextField();
        jblNombreFruta = new javax.swing.JLabel();
        textNombreFruta = new javax.swing.JTextField();
        jblPrecio = new javax.swing.JLabel();
        textPrecioFrutas = new javax.swing.JTextField();
        btnAnadirFruta = new javax.swing.JButton();
        btnRegistrarPedido = new javax.swing.JButton();
        pnlPedidos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCedulas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        pnlCliente.setName(""); // NOI18N

        jblNombre.setText("NOMBRE: ");

        jblCedula.setText("CEDULA:");

        jblListaFrutas.setText("LISTA DE FRUTAS:");

        cbListaFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListaFrutasActionPerformed(evt);
            }
        });

        jblCodigoFrutas.setText("CODIGO:");

        jblNombreFruta.setText("NOMBRE:");

        textNombreFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreFrutaActionPerformed(evt);
            }
        });

        jblPrecio.setText("PRECIO:");

        textPrecioFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioFrutasActionPerformed(evt);
            }
        });

        btnAnadirFruta.setText("AÑADIR FRUTA AL PEDIDO");
        btnAnadirFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirFrutaActionPerformed(evt);
            }
        });

        btnRegistrarPedido.setText("REGISTRAR PEDIDO");
        btnRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPedidoActionPerformed(evt);
            }
        });

        pnlPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedidos Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jLabel1.setText("LISTA DE CCEDULAS:");

        javax.swing.GroupLayout pnlPedidosLayout = new javax.swing.GroupLayout(pnlPedidos);
        pnlPedidos.setLayout(pnlPedidosLayout);
        pnlPedidosLayout.setHorizontalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPedidosLayout.setVerticalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(397, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(btnRegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(jblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(jblCedula)
                        .addGap(18, 18, 18)
                        .addComponent(textCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(jblCodigoFrutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCodigoFrutas))
                    .addComponent(jblListaFrutas))
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cbListaFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAnadirFruta)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addComponent(jblNombreFruta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textNombreFruta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(textPrecioFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(pnlPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNombre)
                    .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblListaFrutas)
                    .addComponent(cbListaFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCedula)
                    .addComponent(textCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblCodigoFrutas)
                    .addComponent(textCodigoFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombreFruta)
                    .addComponent(textNombreFruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblPrecio)
                    .addComponent(textPrecioFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnadirFruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnRegistrarPedido)
                .addGap(29, 29, 29)
                .addComponent(pnlPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreFrutaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_textNombreFrutaActionPerformed

    private void textPrecioFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioFrutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecioFrutasActionPerformed

    private void btnRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPedidoActionPerformed
        // TODO add your handling code here:
        
        
       
   
        
    }//GEN-LAST:event_btnRegistrarPedidoActionPerformed

    private void cbListaFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListaFrutasActionPerformed
        // TODO add your handling code here:
        
        
        //comparacion con cada atributo del combo o si me pide todos generales  
    }//GEN-LAST:event_cbListaFrutasActionPerformed

    private void btnAnadirFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirFrutaActionPerformed
        // TODO add your handling code here:
        String nombreUsuario=textNombreUsuario.getText();
        String cedula=textCedulaUsuario.getText();
        
        
        if(nombreUsuario==" "||cedula==" "){
          
           JOptionPane.showMessageDialog(rootPane, "INGRESE CORRECTAMENTE NOMBRE Y CEDULA DE CLIENTE");
                
        }else{
        Cliente objCliente= new Cliente(nombreUsuario, cedula);
        clientes.add(objCliente);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnAnadirFrutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirFruta;
    private javax.swing.JButton btnRegistrarPedido;
    private javax.swing.JComboBox<String> cbListaFrutas;
    private javax.swing.JComboBox<String> cmbCedulas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jblCedula;
    private javax.swing.JLabel jblCodigoFrutas;
    private javax.swing.JLabel jblListaFrutas;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JLabel jblNombreFruta;
    private javax.swing.JLabel jblPrecio;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JTextField textCedulaUsuario;
    private javax.swing.JTextField textCodigoFrutas;
    private javax.swing.JTextField textNombreFruta;
    private javax.swing.JTextField textNombreUsuario;
    private javax.swing.JTextField textPrecioFrutas;
    // End of variables declaration//GEN-END:variables
}
